name: Update gist with new hitokoto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 6f7cad6485059cd29feb1285f2f01468
      CATEGORY: 
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out
      uses: actions/checkout@v2

    - name: Update gist
      run: go run .
